---
language: objective-c

before_script:
  - sudo easy_install cpp-coveralls

script: 
 - xctool -project DTFoundation.xcodeproj -scheme "DTSidePanels Demo" build -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO
 - xctool -project DTFoundation.xcodeproj -scheme "DTReachability Demo" build -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO
 - xctool -project DTFoundation.xcodeproj -scheme "DTZipArchive Demo" build -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO
# - xctool -project DTFoundation.xcodeproj -scheme "Static Library" build test -sdk iphonesimulator6.1 -arch i386 ONLY_ACTIVE_ARCH=NO -configuration Coverage
 - xcodebuild -scheme "Static Library" -sdk iphonesimulator test -arch x86_64 -destination "platform=iOS Simulator,name=iPhone Retina (4-inch 64-bit),OS=7.1"

after_success:
  - ./coveralls.rb --extension m --exclude-folder Demo --exclude-folder Test --exclude-folder Externals
