---
language: objective-c

before_script:
  - sudo easy_install cpp-coveralls

script:
  - xctool -project DTFoundation.xcodeproj -scheme "Static Library" build test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

after_success:
  - ./coveralls.rb --exclude-folder Demo --exclude-folder Test --exclude-folder Externals --exclude-headers
